-- b_states
insert into b_states (state_code,state_name) values ('AL','Alabama');
insert into b_states (state_code,state_name) values ('AK','Alaska');
insert into b_states (state_code,state_name) values ('AS','American Samoa');
insert into b_states (state_code,state_name) values ('AZ','Arizona');
insert into b_states (state_code,state_name) values ('AR','Arkansas');
insert into b_states (state_code,state_name) values ('CA','California');
insert into b_states (state_code,state_name) values ('CO','Colorado');
insert into b_states (state_code,state_name) values ('CT','Connecticut');
insert into b_states (state_code,state_name) values ('DE','Delaware');
insert into b_states (state_code,state_name) values ('DC','District of Columbia');
insert into b_states (state_code,state_name) values ('FM','Federated States of Micronesia');
insert into b_states (state_code,state_name) values ('FL','Florida');
insert into b_states (state_code,state_name) values ('GA','Georgia');
insert into b_states (state_code,state_name) values ('GU','Guam');
insert into b_states (state_code,state_name) values ('HI','Hawaii');
insert into b_states (state_code,state_name) values ('ID','Idaho');
insert into b_states (state_code,state_name) values ('IL','Illinois');
insert into b_states (state_code,state_name) values ('IN','Indiana');
insert into b_states (state_code,state_name) values ('IA','Iowa');
insert into b_states (state_code,state_name) values ('KS','Kansas');
insert into b_states (state_code,state_name) values ('KY','Kentucky');
insert into b_states (state_code,state_name) values ('LA','Louisiana');
insert into b_states (state_code,state_name) values ('ME','Maine');
insert into b_states (state_code,state_name) values ('MH','Marshall Islands');
insert into b_states (state_code,state_name) values ('MD','Maryland');
insert into b_states (state_code,state_name) values ('MA','Massachusetts');
insert into b_states (state_code,state_name) values ('MI','Michigan');
insert into b_states (state_code,state_name) values ('MN','Minnesota');
insert into b_states (state_code,state_name) values ('MS','Mississippi');
insert into b_states (state_code,state_name) values ('MO','Missouri');
insert into b_states (state_code,state_name) values ('MT','Montana');
insert into b_states (state_code,state_name) values ('NE','Nebraska');
insert into b_states (state_code,state_name) values ('NV','Nevada');
insert into b_states (state_code,state_name) values ('NH','New Hampshire');
insert into b_states (state_code,state_name) values ('NJ','New Jersey');
insert into b_states (state_code,state_name) values ('NM','New Mexico');
insert into b_states (state_code,state_name) values ('NY','New York');
insert into b_states (state_code,state_name) values ('NC','North Carolina');
insert into b_states (state_code,state_name) values ('ND','North Dakota');
insert into b_states (state_code,state_name) values ('MP','Northern Mariana Islands');
insert into b_states (state_code,state_name) values ('OH','Ohio');
insert into b_states (state_code,state_name) values ('OK','Oklahoma');
insert into b_states (state_code,state_name) values ('OR','Oregon');
insert into b_states (state_code,state_name) values ('PW','Palau');
insert into b_states (state_code,state_name) values ('PA','Pennsylvania');
insert into b_states (state_code,state_name) values ('PR','Puerto Rico');
insert into b_states (state_code,state_name) values ('RI','Rhode Island');
insert into b_states (state_code,state_name) values ('SC','South Carolina');
insert into b_states (state_code,state_name) values ('SD','South Dakota');
insert into b_states (state_code,state_name) values ('TN','Tennessee');
insert into b_states (state_code,state_name) values ('TX','Texas');
insert into b_states (state_code,state_name) values ('UT','Utah');
insert into b_states (state_code,state_name) values ('VT','Vermont');
insert into b_states (state_code,state_name) values ('VI','Virgin Islands');
insert into b_states (state_code,state_name) values ('VA','Virginia');
insert into b_states (state_code,state_name) values ('WA','Washington');
insert into b_states (state_code,state_name) values ('WV','West Virginia');
insert into b_states (state_code,state_name) values ('WI','Wisconsin');
insert into b_states (state_code,state_name) values ('WY','Wyoming');

-- b_countries
insert into b_countries values ('AF', 'Afghanistan');
insert into b_countries values ('AL', 'Albania');
insert into b_countries values ('DZ', 'Algeria');
insert into b_countries values ('DS', 'American Samoa');
insert into b_countries values ('AD', 'Andorra');
insert into b_countries values ('AO', 'Angola');
insert into b_countries values ('AI', 'Anguilla');
insert into b_countries values ('AQ', 'Antarctica');
insert into b_countries values ('AG', 'Antigua and Barbuda');
insert into b_countries values ('AR', 'Argentina');
insert into b_countries values ('AM', 'Armenia');
insert into b_countries values ('AW', 'Aruba');
insert into b_countries values ('AU', 'Australia');
insert into b_countries values ('AT', 'Austria');
insert into b_countries values ('AZ', 'Azerbaijan');
insert into b_countries values ('BS', 'Bahamas');
insert into b_countries values ('BH', 'Bahrain');
insert into b_countries values ('BD', 'Bangladesh');
insert into b_countries values ('BB', 'Barbados');
insert into b_countries values ('BY', 'Belarus');
insert into b_countries values ('BE', 'Belgium');
insert into b_countries values ('BZ', 'Belize');
insert into b_countries values ('BJ', 'Benin');
insert into b_countries values ('BM', 'Bermuda');
insert into b_countries values ('BT', 'Bhutan');
insert into b_countries values ('BO', 'Bolivia');
insert into b_countries values ('BA', 'Bosnia and Herzegovina');
insert into b_countries values ('BW', 'Botswana');
insert into b_countries values ('BV', 'Bouvet Island');
insert into b_countries values ('BR', 'Brazil');
insert into b_countries values ('IO', 'British Indian Ocean Territory');
insert into b_countries values ('BN', 'Brunei Darussalam');
insert into b_countries values ('BG', 'Bulgaria');
insert into b_countries values ('BF', 'Burkina Faso');
insert into b_countries values ('BI', 'Burundi');
insert into b_countries values ('KH', 'Cambodia');
insert into b_countries values ('CM', 'Cameroon');
insert into b_countries values ('CA', 'Canada');
insert into b_countries values ('CV', 'Cape Verde');
insert into b_countries values ('KY', 'Cayman Islands');
insert into b_countries values ('CF', 'Central African Republic');
insert into b_countries values ('TD', 'Chad');
insert into b_countries values ('CL', 'Chile');
insert into b_countries values ('CN', 'China');
insert into b_countries values ('CX', 'Christmas Island');
insert into b_countries values ('CC', 'Cocos (Keeling) Islands');
insert into b_countries values ('CO', 'Colombia');
insert into b_countries values ('KM', 'Comoros');
insert into b_countries values ('CG', 'Congo');
insert into b_countries values ('CK', 'Cook Islands');
insert into b_countries values ('CR', 'Costa Rica');
insert into b_countries values ('HR', 'Croatia (Hrvatska)');
insert into b_countries values ('CU', 'Cuba');
insert into b_countries values ('CY', 'Cyprus');
insert into b_countries values ('CZ', 'Czech Republic');
insert into b_countries values ('DK', 'Denmark');
insert into b_countries values ('DJ', 'Djibouti');
insert into b_countries values ('DM', 'Dominica');
insert into b_countries values ('DO', 'Dominican Republic');
insert into b_countries values ('TP', 'East Timor');
insert into b_countries values ('EC', 'Ecuador');
insert into b_countries values ('EG', 'Egypt');
insert into b_countries values ('SV', 'El Salvador');
insert into b_countries values ('GQ', 'Equatorial Guinea');
insert into b_countries values ('ER', 'Eritrea');
insert into b_countries values ('EE', 'Estonia');
insert into b_countries values ('ET', 'Ethiopia');
insert into b_countries values ('FK', 'Falkland Islands (Malvinas)');
insert into b_countries values ('FO', 'Faroe Islands');
insert into b_countries values ('FJ', 'Fiji');
insert into b_countries values ('FI', 'Finland');
insert into b_countries values ('FR', 'France');
insert into b_countries values ('FX', 'France, Metropolitan');
insert into b_countries values ('GF', 'French Guiana');
insert into b_countries values ('PF', 'French Polynesia');
insert into b_countries values ('TF', 'French Southern Territories');
insert into b_countries values ('GA', 'Gabon');
insert into b_countries values ('GM', 'Gambia');
insert into b_countries values ('GE', 'Georgia');
insert into b_countries values ('DE', 'Germany');
insert into b_countries values ('GH', 'Ghana');
insert into b_countries values ('GI', 'Gibraltar');
insert into b_countries values ('GK', 'Guernsey');
insert into b_countries values ('GR', 'Greece');
insert into b_countries values ('GL', 'Greenland');
insert into b_countries values ('GD', 'Grenada');
insert into b_countries values ('GP', 'Guadeloupe');
insert into b_countries values ('GU', 'Guam');
insert into b_countries values ('GT', 'Guatemala');
insert into b_countries values ('GN', 'Guinea');
insert into b_countries values ('GW', 'Guinea-Bissau');
insert into b_countries values ('GY', 'Guyana');
insert into b_countries values ('HT', 'Haiti');
insert into b_countries values ('HM', 'Heard and Mc Donald Islands');
insert into b_countries values ('HN', 'Honduras');
insert into b_countries values ('HK', 'Hong Kong');
insert into b_countries values ('HU', 'Hungary');
insert into b_countries values ('IS', 'Iceland');
insert into b_countries values ('IN', 'India');
insert into b_countries values ('IM', 'Isle of Man');
insert into b_countries values ('ID', 'Indonesia');
insert into b_countries values ('IR', 'Iran (Islamic Republic of)');
insert into b_countries values ('IQ', 'Iraq');
insert into b_countries values ('IE', 'Ireland');
insert into b_countries values ('IL', 'Israel');
insert into b_countries values ('IT', 'Italy');
insert into b_countries values ('CI', 'Ivory Coast');
insert into b_countries values ('JE', 'Jersey');
insert into b_countries values ('JM', 'Jamaica');
insert into b_countries values ('JP', 'Japan');
insert into b_countries values ('JO', 'Jordan');
insert into b_countries values ('KZ', 'Kazakhstan');
insert into b_countries values ('KE', 'Kenya');
insert into b_countries values ('KI', 'Kiribati');
insert into b_countries values ('KP', 'Korea, Democratic People''s Republic of');
insert into b_countries values ('KR', 'Korea, Republic of');
insert into b_countries values ('XK', 'Kosovo');
insert into b_countries values ('KW', 'Kuwait');
insert into b_countries values ('KG', 'Kyrgyzstan');
insert into b_countries values ('LA', 'Lao People''s Democratic Republic');
insert into b_countries values ('LV', 'Latvia');
insert into b_countries values ('LB', 'Lebanon');
insert into b_countries values ('LS', 'Lesotho');
insert into b_countries values ('LR', 'Liberia');
insert into b_countries values ('LY', 'Libyan Arab Jamahiriya');
insert into b_countries values ('LI', 'Liechtenstein');
insert into b_countries values ('LT', 'Lithuania');
insert into b_countries values ('LU', 'Luxembourg');
insert into b_countries values ('MO', 'Macau');
insert into b_countries values ('MK', 'Macedonia');
insert into b_countries values ('MG', 'Madagascar');
insert into b_countries values ('MW', 'Malawi');
insert into b_countries values ('MY', 'Malaysia');
insert into b_countries values ('MV', 'Maldives');
insert into b_countries values ('ML', 'Mali');
insert into b_countries values ('MT', 'Malta');
insert into b_countries values ('MH', 'Marshall Islands');
insert into b_countries values ('MQ', 'Martinique');
insert into b_countries values ('MR', 'Mauritania');
insert into b_countries values ('MU', 'Mauritius');
insert into b_countries values ('TY', 'Mayotte');
insert into b_countries values ('MX', 'Mexico');
insert into b_countries values ('FM', 'Micronesia, Federated States of');
insert into b_countries values ('MD', 'Moldova, Republic of');
insert into b_countries values ('MC', 'Monaco');
insert into b_countries values ('MN', 'Mongolia');
insert into b_countries values ('ME', 'Montenegro');
insert into b_countries values ('MS', 'Montserrat');
insert into b_countries values ('MA', 'Morocco');
insert into b_countries values ('MZ', 'Mozambique');
insert into b_countries values ('MM', 'Myanmar');
insert into b_countries values ('NA', 'Namibia');
insert into b_countries values ('NR', 'Nauru');
insert into b_countries values ('NP', 'Nepal');
insert into b_countries values ('NL', 'Netherlands');
insert into b_countries values ('AN', 'Netherlands Antilles');
insert into b_countries values ('NC', 'New Caledonia');
insert into b_countries values ('NZ', 'New Zealand');
insert into b_countries values ('NI', 'Nicaragua');
insert into b_countries values ('NE', 'Niger');
insert into b_countries values ('NG', 'Nigeria');
insert into b_countries values ('NU', 'Niue');
insert into b_countries values ('NF', 'Norfolk Island');
insert into b_countries values ('MP', 'Northern Mariana Islands');
insert into b_countries values ('NO', 'Norway');
insert into b_countries values ('OM', 'Oman');
insert into b_countries values ('PK', 'Pakistan');
insert into b_countries values ('PW', 'Palau');
insert into b_countries values ('PS', 'Palestine');
insert into b_countries values ('PA', 'Panama');
insert into b_countries values ('PG', 'Papua New Guinea');
insert into b_countries values ('PY', 'Paraguay');
insert into b_countries values ('PE', 'Peru');
insert into b_countries values ('PH', 'Philippines');
insert into b_countries values ('PN', 'Pitcairn');
insert into b_countries values ('PL', 'Poland');
insert into b_countries values ('PT', 'Portugal');
insert into b_countries values ('PR', 'Puerto Rico');
insert into b_countries values ('QA', 'Qatar');
insert into b_countries values ('RE', 'Reunion');
insert into b_countries values ('RO', 'Romania');
insert into b_countries values ('RU', 'Russian Federation');
insert into b_countries values ('RW', 'Rwanda');
insert into b_countries values ('KN', 'Saint Kitts and Nevis');
insert into b_countries values ('LC', 'Saint Lucia');
insert into b_countries values ('VC', 'Saint Vincent and the Grenadines');
insert into b_countries values ('WS', 'Samoa');
insert into b_countries values ('SM', 'San Marino');
insert into b_countries values ('ST', 'Sao Tome and Principe');
insert into b_countries values ('SA', 'Saudi Arabia');
insert into b_countries values ('SN', 'Senegal');
insert into b_countries values ('RS', 'Serbia');
insert into b_countries values ('SC', 'Seychelles');
insert into b_countries values ('SL', 'Sierra Leone');
insert into b_countries values ('SG', 'Singapore');
insert into b_countries values ('SK', 'Slovakia');
insert into b_countries values ('SI', 'Slovenia');
insert into b_countries values ('SB', 'Solomon Islands');
insert into b_countries values ('SO', 'Somalia');
insert into b_countries values ('ZA', 'South Africa');
insert into b_countries values ('GS', 'South Georgia South Sandwich Islands');
insert into b_countries values ('ES', 'Spain');
insert into b_countries values ('LK', 'Sri Lanka');
insert into b_countries values ('SH', 'St. Helena');
insert into b_countries values ('PM', 'St. Pierre and Miquelon');
insert into b_countries values ('SD', 'Sudan');
insert into b_countries values ('SR', 'Suriname');
insert into b_countries values ('SJ', 'Svalbard and Jan Mayen Islands');
insert into b_countries values ('SZ', 'Swaziland');
insert into b_countries values ('SE', 'Sweden');
insert into b_countries values ('CH', 'Switzerland');
insert into b_countries values ('SY', 'Syrian Arab Republic');
insert into b_countries values ('TW', 'Taiwan');
insert into b_countries values ('TJ', 'Tajikistan');
insert into b_countries values ('TZ', 'Tanzania, United Republic of');
insert into b_countries values ('TH', 'Thailand');
insert into b_countries values ('TG', 'Togo');
insert into b_countries values ('TK', 'Tokelau');
insert into b_countries values ('TO', 'Tonga');
insert into b_countries values ('TT', 'Trinidad and Tobago');
insert into b_countries values ('TN', 'Tunisia');
insert into b_countries values ('TR', 'Turkey');
insert into b_countries values ('TM', 'Turkmenistan');
insert into b_countries values ('TC', 'Turks and Caicos Islands');
insert into b_countries values ('TV', 'Tuvalu');
insert into b_countries values ('UG', 'Uganda');
insert into b_countries values ('UA', 'Ukraine');
insert into b_countries values ('AE', 'United Arab Emirates');
insert into b_countries values ('GB', 'United Kingdom');
insert into b_countries values ('US', 'United States');
insert into b_countries values ('UM', 'United States minor outlying islands');
insert into b_countries values ('UY', 'Uruguay');
insert into b_countries values ('UZ', 'Uzbekistan');
insert into b_countries values ('VU', 'Vanuatu');
insert into b_countries values ('VA', 'Vatican City State');
insert into b_countries values ('VE', 'Venezuela');
insert into b_countries values ('VN', 'Vietnam');
insert into b_countries values ('VG', 'Virgin Islands (British)');
insert into b_countries values ('VI', 'Virgin Islands (U.S.)');
insert into b_countries values ('WF', 'Wallis and Futuna Islands');
insert into b_countries values ('EH', 'Western Sahara');
insert into b_countries values ('YE', 'Yemen');
insert into b_countries values ('ZR', 'Zaire');
insert into b_countries values ('ZM', 'Zambia');
insert into b_countries values ('ZW', 'Zimbabwe');